ItsyDev.ApplicationService.WebPage/Models/ErrorViewModel.cs
namespace ItsyDev.ApplicationService.WebPage.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ItsyDev.ApplicationService.WebPage/Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Mvc;

namespace ItsyDev.ApplicationServices.WebPage.Controllers;

public class AboutUsController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

ItsyDev.ApplicationService.WebPage/Controllers/EventosController.cs
using Microsoft.AspNetCore.Mvc;

namespace ItsyDev.ApplicationServices.WebPage.Controllers;

public class EventosController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

ItsyDev.ApplicationService.WebPage/Controllers/ExperienceDetailController.cs
using System;
using System.Threading.Tasks;
using ItsyDev.ApplicationServices.Models.Experiences;
using ItsyDev.ApplicationServices.Services.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace ItsyDev.ApplicationServices.WebPage.Controllers;

public class ExperienceDetailController : Controller
{
    private readonly IExperienceService _experienceService;

    public ExperienceDetailController(IExperienceService experienceService)
    {
        _experienceService = experienceService;
    }

    public async Task<IActionResult> Index(int? experienceId)
    {
        try
        {
            var id = -1;
            if (experienceId.HasValue) id = experienceId.Value;
            var experience = await GetExperienceById(id);
            View(experience);
        }
        catch (ArgumentNullException ex)
        {
        }

        return View();
    }

    public async Task<ExperienceViewModel> GetExperienceById(int experienceId)
    {
        return await _experienceService.GetExperienceById(experienceId);
    }
}

ItsyDev.ApplicationService.WebPage/Controllers/ExperiencesController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using ItsyDev.ApplicationServices.Models.Experiences;
using ItsyDev.ApplicationServices.Models.Materials;
using ItsyDev.ApplicationServices.Models.UI_Models;
using ItsyDev.ApplicationServices.Services.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace ItsyDev.ApplicationServices.WebPage.Controllers;

public class ExperiencesController : Controller
{
    private readonly IExperienceService _experienceService;
    private readonly List<ExperienceCategoryViewModel>? _experienceCategories;
    private readonly List<MaterialViewModel>? _experienceMaterials;

    public ExperiencesController(IExperienceService experienceService)
    {
        _experienceService = experienceService;
        _experienceCategories = new List<ExperienceCategoryViewModel>();
        _experienceMaterials = new List<MaterialViewModel>();
    }

    public async Task<IActionResult> Index()
    {
        var experiences = await _experienceService.GetExperiences();
        return View(new ExperienceListModel
        {
            Experiences = experiences
        });
    }

    public IActionResult FilterExperiences()
    {
        return RedirectToAction("Index");
    }

    public async Task<List<ExperienceViewModel>> GetExperiences()
    {
        var result = await _experienceService.GetExperiences();
        return result.Count >= 1 ? result : new List<ExperienceViewModel>();
    }

    public List<MaterialViewModel>? GetExperienceHeadsets(List<ExperienceViewModel> experiences)
    {
        if (_experienceMaterials is not { Count: 0 }) return _experienceMaterials;
        if (experiences.Count == 0)
            return new List<MaterialViewModel>();
        var headsets = _experienceService.GetAvailableHeadsetsByExperiences(experiences);
        return headsets;
    }

    public List<ExperienceCategoryViewModel>? GetExperienceCategories(List<ExperienceViewModel> experiences)
    {
        if (_experienceCategories is not { Count: 0 }) return _experienceCategories;
        if (experiences.Count == 0)
            return new List<ExperienceCategoryViewModel>();
        var categories = _experienceService.GetAvailableCategoriesByExperiences(experiences);
        return categories;
    }
}

ItsyDev.ApplicationService.WebPage/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ItsyDev.ApplicationServices.WebPage.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

ItsyDev.ApplicationService.WebPage/Controllers/ImagesController.cs
using System.Threading.Tasks;
using ItsyDev.ApplicationServices.Services.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace ItsyDev.ApplicationServices.WebPage.Controllers;

public class ImagesController : Controller
{
    private readonly IImageService _imageService;

    public ImagesController(IImageService imageService)
    {
        _imageService = imageService;
    }

    public async Task<IActionResult> Index()
    {
        var result = await _imageService.GetImages();
        return View(result);
    }
}

ItsyDev.ApplicationService.WebPage/Views/AboutUs/Index.cshtml
@{
    ViewData["Title"] = "Sobre nosotros";
}

<link rel="stylesheet" href="./css/components.css"/>
<link rel="stylesheet" href="./css/aboutus.css"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<div class="text-center">
    <h1 class="display-4">Sobre nosotros</h1>
    <container>
        <h2>¿Qué es el club de realidad virtual?</h2>
        <p>
            El club de Realidad Virtual es una iniciativa impulsada por el instituto IES Esteve Terradas en el 2019 para
            impulsar el desarrollo y la utilización de la realidad virtual en las aulas y en los centros de estudios para
            la mejora de la forma en la que se enseña en los centros.
        </p>
    </container>
    <span>
        <h2>Preguntas frequentes</h2>
    </span>
    <container>
        <article>
            <h2>¿Qué hacemos en el Club de Realidad Virtual?</h2>
            <p>En el club</p>
        </article>
    </container>
</div>

ItsyDev.ApplicationService.WebPage/Views/Eventos/Index.cshtml
@{
    ViewData["Title"] = "Eventos";
}

<link rel="stylesheet" href="./css/components.css"/>
<link rel="stylesheet" href="./css/events.css"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<main class="main-container">
<section id="servicios" class="py-5">
    <div class="container">
        <h2>Eventos del Club</h2>
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <img src="https://raw.githubusercontent.com/itsivanpsk/clubvrassets/master/vtol_1.jpg" alt="Servicio 1" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">Carnaval</h5>
                        <p class="card-text">
                            El club de realidad virtual realiza un evento en el día de castañada en el centro IES Esteve Terradas,
                            en este evento mostramos al público experiencias de realidad virtual orientadas a la festividad.
                        </p>
                        <a href="#Carnaval" class="btn btn-primary">Leer Más</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <img src="https://raw.githubusercontent.com/itsivanpsk/clubvrassets/master/vtol_1.jpg" alt="Servicio 1" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">Citi Lab</h5>
                        <p class="card-text">
                            La fira apropat es una feria orientada a descubrir las diferentes salidas de los ciclos de
                            formación profesional. El club de realidad virtual proporciona a las personas que se acercan
                            a la feria experiencias educativas.

                        </p>
                        <a href="#CitiLab" class="btn btn-primary">Leer Más</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <img src="https://raw.githubusercontent.com/itsivanpsk/clubvrassets/master/vtol_1.jpg" alt="Servicio 1" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">Castañada</h5>
                        <p class="card-text">
                            El club de realidad virtual realiza un evento en el día de carnaval en el centro IES Esteve Terradas,
                            en este evento mostramos al público experiencias de realidad virtual diferentes.
                        </p>
                        <a href="#Castañada" class="btn btn-primary">Leer Más</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <img src="https://raw.githubusercontent.com/itsivanpsk/clubvrassets/master/vtol_1.jpg" alt="Servicio 1" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">Semana de orientación</h5>
                        <p class="card-text">
                            Durante una semana al año, el centro IES Esteve Terradas realiza una jornada en
                            las que diferentes empresas proporcionan visitas, muestras o exposiciones a los
                            alumnos para mostrar diferentes salidas al mundo laboral tras la ESO y/o el batchiller.
                            El club de realidad virtual desde el 2021 se ha unido a esta jornada mostrando
                            a los alumnos las salidas que existen en el mundo de la informatica relacionada con la realidad virtual.
                        </p>
                        <a href="#Orientación" class="btn btn-primary">Leer Más</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="events-list">
    <h2>Eventos</h2>
    <h3 id="#2023">2023</h3>
    <hr class="div-line">
    <div class="age-event">
        <article>
            <h4>Castañada 2023</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            </p>
            <a href="/Images#2023" class="btn btn-primary">Imágenes</a>
        </article>
        <article>
            <h4>Soria Salud VR</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            </p>
            <a href="/Images#2023" class="btn btn-primary">Imágenes</a>
        </article>
        <article>
            <h4>Fira Apropat (CitiLab) 2023</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            </p>
            <a href="/Images#2023" class="btn btn-primary">Imágenes</a>
        </article>
        <article>
            <h4>Carnaval 2023</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            </p>
            <a href="/Images#2023" class="btn btn-primary">Imágenes</a>
        </article>
    </div>
    <h3 id="#2022">2022</h3>
    <hr class="div-line">
    <div class="age-event">
        <article>
            <h4>Castañada 2022</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            </p>
            <a href="/Images#2022" class="btn btn-primary">Imágenes</a>
        </article>
        <article>
            <h4>Fira Apropat 2022</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            </p>
            <a href="/Images#2022" class="btn btn-primary">Imágenes</a>
        </article>
        <article>
            <h4>Orientación académica 2022</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            </p>
            <a href="/Images#2022" class="btn btn-primary">Imágenes</a>
        </article>
        <article>
            <h4>Carnaval 2022</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            </p>
            <a href="/Images#2022" class="btn btn-primary">Imágenes</a>
        </article>
    </div>
    <h3 id="#2021">2021</h3>
    <hr class="div-line">
    <div class="age-event">
        <article>
            <h4>Castañada 2021</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            </p>
            <a href="/Images#2021" class="btn btn-primary">Imágenes</a>
        </article>
        <article>
            <h4>Fira Apropat 2021</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            </p>
            <a href="/Images#2021" class="btn btn-primary">Imágenes</a>
        </article>
        <article>
            <h4>Carnaval 2021</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            </p>
            <a href="/Images#2021" class="btn btn-primary">Imágenes</a>
        </article>
    </div>
    <h3 id="#2020">2020</h3>
    <hr class="div-line">
    <div class="age-event">
        <article>
            <h4>Castañada 2020</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            </p>
            <a href="/Images#2020" class="btn btn-primary">Imágenes</a>
        </article>
        <article>
            <h4>Fira Apropat 2020</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            </p>
            <a href="/Images#2020" class="btn btn-primary">Imágenes</a>
        </article>
        <article>
            <h4>Carnaval 2020</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            </p>
            <a href="/Images#2020" class="btn btn-primary">Imágenes</a>
        </article>
    </div>
    <h3 id="#2019">2019</h3>
    <hr class="div-line">
    <div class="age-event">
        <article>
            <h4>Castañada 2019</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            </p>
            <a href="/Images#2019" class="btn btn-primary">Imágenes</a>
        </article>
    </div>
</section>
</main>

ItsyDev.ApplicationService.WebPage/Views/ExperienceDetail/Index.cshtml
@model ItsyDev.ApplicationServices.Models.Experiences.ExperienceViewModel

@{
    ViewData["Title"] = "Experience Detail";
}

<link rel="stylesheet" href="./css/components.css"/>
<link rel="stylesheet" href="./css/experiencedetail.css"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<main>
    <container>
        @if (Model.Images != null && Model.Images.Any())
        {
            <img src="@Model.Images[0].Src" class="experience-image" alt="@Model.Name"/>
        }
        <h1>@Model.Name</h1>
        @if (Model.Categories != null && Model.Categories.Any())
        {
            <h2>@string.Join(", ", Model.Categories.Select(c => c.Name))</h2>
        }
        <h3>@Model.Rating</h3>
    </container>
</main>

ItsyDev.ApplicationService.WebPage/Views/Experiences/Index.cshtml
@model ItsyDev.ApplicationServices.Models.UI_Models.ExperienceListModel;

@{
    ViewData["Title"] = "Experiencias";
}

<link rel="stylesheet" href="./css/components.css"/>
<link rel="stylesheet" href="./css/experiences.css"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<main>
    <section class="experiences-banner-section">
        <img class="experiences-banner-image" src="" alt=""/>
        <h1>Experiencias</h1>
        <h3>Nuestras experiencias</h3>
        <form method="get" asp-controller="AboutUs" asp-action="Index">
            <button type="submit" class="btn btn-primary">Sobre nosotros</button>
        </form>
    </section>
    <container class="experience-container">
        <section class="experience-section">
            @if (Model.Experiences != null)
            {
                @foreach (var experience in Model.Experiences)
                {
                    <article class="experience-item">
                        @if (experience.Images != null && experience.Images.Any())
                        {
                            <img src="@experience.Images[0].Src" class="experience-image" alt="@experience.Name"/>
                        }
                        <p class="experience-name">@experience.Name</p>
                        @if (experience.Categories != null && experience.Categories.Any())
                        {
                            <p class="experience-categories">
                                @string.Join(
                                    ", ",
                                    experience.Categories.Select(
                                        c => c.Name
                                        )
                                    )
                            </p>
                        }
                        <form method="get" asp-controller="ExperienceDetail" asp-action="Index">
                            <input type="hidden" name="experienceId" value="@experience.Id"/>
                            <button type="submit" class="btn btn-primary">Ver más</button>
                        </form>
                    </article>
                }
            }
        </section>
    </container>
</main>

ItsyDev.ApplicationService.WebPage/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<link rel="stylesheet" href="./css/components.css"/>
<link rel="stylesheet" href="./css/home.css"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<container class="m-container">
    <div id="slider" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="https://raw.githubusercontent.com/ItsIvanPsk/ClubVRAssets/master/Experiences/1-BeatSaber/beat_saber_1.jpg" alt="Imagen 1" class="d-block w-100">
                <div class="carousel-caption">
                    <h3>Beat Saber</h3>
                    <p>Beat saber es un juego rítmico inspirado en el aclamado juego Guitar Hero.</p>
                    <a href="ExperienceDetail?experienceId=1" class="btn btn-primary experience-button">Ver Más</a>
                </div>
            </div>
        </div>
    </div>

    <section id="bienvenida" class="py-5">
        <div class="container">
            <div class="row">
                <div>
                    <h2>Club de Realidad Virtual</h2>
                    <p>El club de realidad virtual es una iniciativa que nace de la necesidad de la divulgación de la realidad virtual.</p>
                    <p>La iniciativa fue impulsada por el centro de educación secundaria IES Esteve Terradas I Illa en 2019</p>
                    <a href="/AboutUs/" class="btn btn-primary">Conócenos Más</a>
                </div>
            </div>
        </div>
    </section>

    <section id="servicios" class="py-5 bg-light">
        <div class="container">
            <h2>Servicios</h2>
            <div class="row">
                <div class="col-md-4">
                    <div class="card">
                        <img src="https://raw.githubusercontent.com/ItsIvanPsk/ClubVRAssets/master/Experiences/1-BeatSaber/beat_saber_1.jpg" alt="Servicio 1" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title">Eventos</h5>
                            <p class="card-text">
                                El club de realidad virtual realiza todo tipo de eventos en diversos espacios para mostrar
                                los nuevos avances de la realidad virtual.
                            </p>
                            <a href="/Eventos" class="btn btn-primary">Leer Más</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <img src="https://raw.githubusercontent.com/ItsIvanPsk/ClubVRAssets/master/Experiences/1-BeatSaber/beat_saber_1.jpg" alt="Servicio 1" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title">Sesiones</h5>
                            <p class="card-text">
                                Las sesiones son una parte fundamental de los servicios del club.
                                Las sesiones permiten disfrutar de la realidad virtual de una forma mas personal.
                            </p>
                            <a href="/Sesiones" class="btn btn-primary">Leer Más</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <img src="https://raw.githubusercontent.com/ItsIvanPsk/ClubVRAssets/master/Experiences/1-BeatSaber/beat_saber_1.jpg" alt="Servicio 1" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title">Desarrollos</h5>
                            <p class="card-text">
                                En el club de realidad virtual desarrollamos todo tipo de experiencias de realidad virtual.
                                Dentro de los desarrollos del club podemos destacar la experiencia del 60th aniversario del comic de Tin tin.
                            </p>
                            <a href="/Desarrollos" class="btn btn-primary">Leer Más</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="py-5">
        <h2>Collaboradores</h2>
        <container id="collaboradores">
            <article>
                <img src="./images/Logo/IETI_LOGO.png" alt="Colaborador: IES Esteve Terradas I Illa"/>
            </article>
            <article>
                <img src="./images/Logo/IETI_LOGO.png" alt="Colaborador: Itsy Dev Studios"/>
            </article>
            <article>
                <img src="./images/Logo/CITILAB_CORNELLA.jpg" alt="Colaborador: Citilab"/>
            </article>
        </container>
    </section>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</container>

ItsyDev.ApplicationService.WebPage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/ItsyDev.ApplicationServices.WebPage.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-transparent border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="/">
                <span class="fas fa-icono-de-bootstrap">
                    <img src="./images/Logo/CVR_LOGO.png" height="35px" width="35px" alt=""/>
                </span>
            </a>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between flex-row-reverse mr-2">
                <ul class="navbar-nav flex-grow-2">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Experiences" asp-action="Index">Experiencias</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="AboutUs" asp-action="Index">Sobre nosotros</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container-fluid">
    <main role="main">
        @RenderBody()
    </main>
</div>

<footer class="cvr-footer border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Club de Realidad Virtual. Powered by Itsy Dev Studios
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>